name: world
favicon: null
layout_spectrum: 0.1633778379764408
typography_spectrum: 0.8986604276578873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#b7b7b7'
    - '#060606'
    - '#454545'
    - '#e79b70'
  brandStrength: 0.5
  lightness: 0.3298359902109951
  saturation: 0.10612339689396322
  rhythmicContrast: 0.24718963960185647
purpose: []
